export enum MenuOptions {
	INDEX = "index",
	LOGIN = "login",
	REGISTER = "register",
	HOME = "home",
	INVENTORY = "inventory",
	TRADE = "trade",
	JOIN_ROOM = "joinRoom",
	RECLAIM_CARDS = "reclaim",
	CREATE_ROOM = "createRoom",
	HELP_TRADE_ROOM = "helpTradeRoom",
	CHOOSE_CARDS_TRADE_ROOM = "chooseCardsTradeRoom",
	NO_AVAILABLE = "no-available",
	RETRY_CONNECTION = "retryConnection",
	EXIT = "exit",
}
